# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\download.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 255,150);")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 60, 581, 461))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.textBrowser.setObjectName("textBrowser")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(470, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("background-color: rgb(255, 255, 0,150);")
        self.cancelButton.setObjectName("cancelButton")
        self.CET4 = QtWidgets.QRadioButton(self.centralwidget)
        self.CET4.setGeometry(QtCore.QRect(10, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CET4.setFont(font)
        self.CET4.setStyleSheet("color: rgb(255, 255, 255);")
        self.CET4.setObjectName("CET4")
        self.CET6 = QtWidgets.QRadioButton(self.centralwidget)
        self.CET6.setGeometry(QtCore.QRect(100, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CET6.setFont(font)
        self.CET6.setStyleSheet("color: rgb(255, 255, 255);")
        self.CET6.setObjectName("CET6")
        self.cancelDownload = QtWidgets.QPushButton(self.centralwidget)
        self.cancelDownload.setGeometry(QtCore.QRect(340, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelDownload.setFont(font)
        self.cancelDownload.setStyleSheet("background-color: rgb(255, 0, 0,150);")
        self.cancelDownload.setObjectName("cancelDownload")
        self.widget_top = QtWidgets.QWidget(self.centralwidget)
        self.widget_top.setGeometry(QtCore.QRect(0, -20, 601, 601))
        self.widget_top.setStyleSheet("background-image: url(:/png_show/image/background.png);")
        self.widget_top.setObjectName("widget_top")
        self.progressBar = QtWidgets.QProgressBar(self.widget_top)
        self.progressBar.setGeometry(QtCore.QRect(10, 550, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.widget_top.raise_()
        self.pushButton.raise_()
        self.textBrowser.raise_()
        self.cancelButton.raise_()
        self.CET4.raise_()
        self.CET6.raise_()
        self.cancelDownload.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setStyleSheet("font: 8pt \"微软雅黑\";\n"
"background-color: rgb(217, 255, 254);\n"
"\n"
"\n"
"")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setCheckable(False)
        self.about.setChecked(False)
        self.about.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.about.setFont(font)
        self.about.setObjectName("about")
        self.menu.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "开始下载"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))
        self.cancelButton.setText(_translate("MainWindow", "退出"))
        self.CET4.setText(_translate("MainWindow", "CET4"))
        self.CET6.setText(_translate("MainWindow", "CET6"))
        self.cancelDownload.setText(_translate("MainWindow", "取消下载"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.about.setText(_translate("MainWindow", "详细信息"))
import png_show_rc
